version: 1.0.{build}
branches:
  only:
  - develop
  - master
before_build:
- cmd: >-
    cd src

    dotnet restore
build:
  verbosity: normal
notifications:
- provider: Email
  to:
  - camposabates@gmail.com
  subject: CI result from ConnNet
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true